#!/bin/sh

passed=0
failed=0

_test() {
  # check if custom command is provided
  args=
  
  if [ -f "$1/file" ]; then
    args="$1/file"
  fi

  tui-puppet "$1/keystream" ./oswald $args > "$1/last_output"

  testname="${1##*/}"
  if cmp "$1/last_output" "$1/output" >/dev/null; then
    printf "\033[42m PASS \033[0m $testname\n"
    : $(( passed = passed + 1 ))
  else
    printf "\033[41m FAIL \033[0m $testname\n"
    status=1
    : $(( failed = failed + 1 ))
  fi
}

printf "\033[100m TESTS                                         \033[0m\n"

for test_dir in tests/*; do
    _test "$test_dir"
done

printf "\033[100m RESULTS                                       \033[0m\n"
printf " PASSED: %04d\n" $passed
printf " FAILED: %04d                           \033[0m\n" $failed

printf "\033[100m STATUS                                        \033[0m\n"
if [ $failed -ne 0 ]; then
  printf "\033[41m                                               \033[0m\n"
  printf "\033[41m             !!! FAILING TESTS !!!             \033[0m\n"
  printf "\033[41m                                               \033[0m\n"
else
  printf "\033[42m                                               \033[0m\n"
  printf "\033[42m                 ALL PASSISNG                  \033[0m\n"
  printf "\033[42m                                               \033[0m\n"
fi


exit "${status:-0}"
PASSED: 0000
FAILED: 0000
